routes/web.php
<?php


Route::get('/','FrontendController@index')->name('home'); 
Route::get('object'.'/{id}','FrontendController@object')->name('object');
Route::post('roomsearch','FrontendController@roomsearch')->name('roomSearch');
Route::get('room'.'/{id}','FrontendController@room')->name('room');
Route::get('article'.'/{id}','FrontendController@article')->name('article');
Route::get('person'.'/{id}','FrontendController@person')->name('person');
 
Route::get('/searchCities', 'FrontendController@searchCities');
Route::get('/ajaxGetRoomReservations/{id}', 'FrontendController@ajaxGetRoomReservations');

Route::get('/like/{likeable_id}/{type}', 'FrontendController@like')->name('like');
Route::get('/unlike/{likeable_id}/{type}', 'FrontendController@unlike')->name('unlike');

Route::post('addComment/{commentable_id}', 'FrontendController@addComment')->name('addComment');
Route::post('/makeReservation/{room_id}/{city_id}', 'FrontendController@makeReservation')->name('makeReservation');

 
Route::group(['prefix'=>'admin','middleware'=>'auth'],function(){ 

  //for json mobile
  Route::get('/getNotifications', 'BackendController@getNotifications'); 
  Route::post('/setReadNotifications', 'BackendController@setReadNotifications'); 
    
  Route::get('/','BackendController@index')->name('adminHome'); 
  Route::get('/myobjects','BackendController@myobjects')->name('myObjects')->middleware('CheckOwner'); 
  Route::match(['GET', 'POST'], 'saveobject'.'/{id?}','BackendController@saveObject')->name('saveObject')->middleware('CheckOwner');
  Route::match(['GET', 'POST'], 'profile','BackendController@profile')->name('profile');
  Route::get('/deletePhoto/{id}', 'BackendController@deletePhoto')->name('deletePhoto');
  Route::get('/deleteArticle/{id}', 'BackendController@deleteArticle')->name('deleteArticle');
  Route::post('/saveArticle/{id?}', 'BackendController@saveArticle')->name('saveArticle');

  Route::match(['GET', 'POST'], trans('routes.saveroom').'/{id?}','BackendController@saveRoom')->name('saveRoom')->middleware('CheckOwner');
  Route::get('deleteroom'.'/{id}', 'BackendController@deleteRoom')->name('deleteRoom');
   
  Route::get('ajaxGetReservationData', 'BackendController@ajaxGetReservationData');
  Route::get('/ajaxSetReadNotification', 'BackendController@ajaxSetReadNotification');
  Route::get('/ajaxGetNotShownNotifications', 'BackendController@ajaxGetNotShownNotifications');
  Route::get('/ajaxSetShownNotifications', 'BackendController@ajaxSetShownNotifications');

  Route::get('/confirmReservation/{id}', 'BackendController@confirmReservation')->name('confirmReservation')->middleware('CheckOwner');
  Route::get('/deleteReservation/{id}', 'BackendController@deleteReservation')->name('deleteReservation'); 

  Route::resource('cities', 'CityController')->middleware('CheckAdmin');

  Route::get('deleteobject'.'/{id}','BackendController@deleteObject')->name('deleteObject')->middleware('CheckOwner');
    
});


Auth::routes();

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link rel="stylesheet" href="https://bootswatch.com/3/readable/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li style="list-style-type:none" class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li style="list-style-type:none" class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/backend.blade.php
<!DOCTYPE html>
<html lang="pl">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Admin panel</title>

        <!-- Bootstrap core CSS -->
        <link href="https://bootswatch.com/3/readable/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">


        <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
        <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
        

        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <script>
            var base_url = '{{ url('/admin') }}';
            <?php
            if ( isset($_COOKIE['scroll_val']) )
            {

                echo 'var scroll_val=' . '"' . (int) $_COOKIE['scroll_val'] . '";' ;
               
                setcookie('scroll_val', '',-3000);

            }
            ?>
        </script>
        
    </head>

    <body>

        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{{ route('home') }}">Hotels App!</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">


                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                @if( $ncounter = count($notifications->where('status',0)) )
                                <span id="app-notifications-count" class="button__badge">{{ $ncounter }}</span>
                                @else
                                <span id="app-notifications-count" class="button__badge hidden">0</span>
                                @endif
                                <span class="glyphicon glyphicon-envelope"></span> <span class="caret"></span></a>
                            <ul id="app-notifications-list" class="dropdown-menu">
                                @foreach( $notifications as $notification )
                                    @if($notification->status)
                                    <li><a>{{ $notification->content }}</a></li>
                                    @else
                                    <li class="unread_notification"><a href="{{ $notification->id }}">{{ $notification->content }}</a></li>
                                    @endif

                                @endforeach

                            </ul>
                        </li>

                        <li><p class="navbar-text">{{ Auth::user()->FullName }}</p></li>
                        <li><a href="{{ route('profile') }}">{{ __('Profile') }}</a></li>
                        <li><a href="{{ route('logout') }}"
                            onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}</a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                            </form>
                        </li>  
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-3 col-md-2 sidebar">
                    <ul class="nav nav-sidebar">
                        <li class="active"><a href="{{ route('adminHome') }}">{{ __('Booking calendar') }} <span class="sr-only">(current)</span></a></li>
                        @if( Auth::user()->hasRole(['owner','admin'])  )
                        <li><a href="{{ route('myObjects') }}">{{ __('My tourist objects') }}</a></li>
                        <li><a href="{{ route('saveObject') }}">{{ __('Add a new tourist object') }}</a></li>
                        @endif
                        @if( Auth::user()->hasRole(['admin']) )
                        <li><a href="{{ route('cities.index') }}">{{ __('Cities') }}</a></li>
                        @endif
                    </ul>
                </div>

                <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                    <br />
                    @if( $errors->any() )

                    <div class="alert alert-danger">
                        <ul>       
                            @foreach ($errors->all() as $error)   

                            <li style="list-style-type: none">{{ $error }}</li>

                            @endforeach
                        </ul> 
                    </div>

                    @endif

                    <br> 
                    
                    @if(Session::has('message'))
                    <br>
                    <div class="alert {{ Session::get('alert-class', 'alert-info') }} alert-dismissible show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        {{ Session::get('message') }}
                    </div>

                    @endif
                    
                    @yield('content')                    
                </div>
            </div>
        </div>

        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
        <script src="{{ asset('js/app.js') }}"></script>
        <script src="{{ asset('js/admin.js') }}"></script>
        @stack('scripts')

        <script>

        $(function () {


        //to prevent scroll top when refreshing
        if (typeof scroll_val !== 'undefined') {

            $(window).scrollTop(scroll_val);
            //scroll(0,scroll_val);
        }

        });


        //to prevent scroll top when refreshing
        function scroll_value()
        {
            document.cookie = 'scroll_val' + '=' + $(window).scrollTop();
        }


        $(document).on('click', '.keep_pos', function (e) {
            scroll_value();
        });

        </script>
        
    </body>
</html>

resources/views/layouts/frontend.blade.php
<!DOCTYPE html>
<html lang="pl">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>HotelsApp!</title>

        <!-- Bootstrap -->
        <link rel="stylesheet" href="https://bootswatch.com/3/readable/bootstrap.min.css" crossorigin="anonymous">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">
     
        <script>
            var base_url = '{{ url('/') }}';
        </script>
        
    </head>
    <body>

        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{{ route('home') }}">{{ __('Home') }}</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    @auth 
                    <ul class="nav navbar-nav navbar-right">
                        <li><p class="navbar-text">{{ __('Hello') }}</p></li>
                        <li><p class="navbar-text">{{ Auth::user()->name }}</p></li>
                        <li><a href="{{ route('adminHome') }}">Panel</a></li>
                        
                        
                        <li>
                        <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                        </li>

                    </ul>
                    @endauth
                    @guest 
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{{ route('login') }}">{{ __('Sign in') }}</a></li>
                        <li><a href="{{ route('register') }}">{{ __('Sign up') }}</a></li>
                    </ul>
                    @endguest
                </div>
            </div>
        </nav>

        <div class="jumbotron">
            <div class="container">
                <h1>Hotels App!</h1>
                <p>Darmowa platforma hotelarska!</p>
                <p>Znajdz nocleg w interesującym Cie miejscu!</p>
                <form method="POST" <?php ?> action="{{ route('roomSearch') }}" class="form-inline">
                    <div class="form-group">
                        <label class="sr-only" for="city">City</label>
                        <input name="city" value="{{ old('city') }}" type="text" class="form-control autocomplete" id="city" placeholder="{{ __('City') }}">
                    </div>
                    <div class="form-group">
                        <label class="sr-only" for="day_in">Check in</label>
                        <input name="check_in" value="{{ old('check_in') }}" type="text" class="form-control datepicker" id="check_in" placeholder="{{ __('Check in') }}">
                    </div>

                    <div class="form-group">
                        <label class="sr-only" for="day_out">Check out</label>
                        <input name="check_out" value="{{ old('check_out') }}" type="text" class="form-control datepicker" id="check_out" placeholder="{{ __('Check out') }}">
                    </div>
                    <div class="form-group">
                        <select name="room_size" class="form-control">
                            <option>{{ __('Room size') }}</option>
                            
                          
                            @for($i=1;$i<=5;$i++)
                                @if( old('room_size') == $i )
                                <option selected value="{{$i}}">{{$i}}</option>
                                @else
                                <option value="{{$i}}">{{$i}} {{ __('persons') }}</option>
                                @endif
                            @endfor
                            
                        </select>
                    </div>
                    <button type="submit" class="btn btn-warning">{{ __('Search') }}</button>                    
                 
                  
                {{ csrf_field() }}
                    
                </form>

            </div>
        </div>

        @yield('content')        

        <hr>

        <footer>

            <p class="text-center">&copy; 2020 HotelsApp</p>

        </footer>      

        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
       
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <script src="{{ asset('js/app.js') }}"></script> 
        @stack('scripts')        

    </body>
</html>